### create an user
POST http://localhost:8080/api/users
accept: application/json
content-type: application/json

{

    "firstName" : "hjhjh",
    "lastName" : "fhghf",
    "email" :"tryrtugjkhk@gmail.com",
    "authorized" : false,
    "password" : "password",
    "status" : "ACTIF"
}