spring:
  application:
    name: manage user's tasks Application
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: groupId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      database: manageTasksDB
      port: 27017

kafka:
  bootstrapAddress: localhost:9092
  general:
    topic:
      name: topicName
      group:
        id: groupId
  user:
    topic:
      name: topicUser
      group:
        id: userGroupId

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
