spring:
  profiles:
    active: dev
  application:
    name: manage user's tasks Application
  webflux:
    multipart:
      max-in-memory-size: 512KB
      max-parts: 3
      max-disk-usage-per-part: 1024KB
      max-headers-size: 5KB

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
